### ISSUE TITLE
Needs a favicon 

### ISSUE THREAD

**Issue by georgically** [PyConTH/www2021#15]
## No favicon on website 

Favicon is missing. 

Add favicon using https://realfavicongenerator.net/ to generate with logo found on: https://www.notion.so/pyconth/Logos-and-guidelines-1cc44fc694c74ecc92d30017a6f6a257#ed724ed2fd3b4aedb123d1abc90f6cb9

Found this article about missing favicon on elegant theme. That should be able to solve the issue:

http://archerimagine.com/articles/pelican/integration-problem-with-elegant-theme.html

**Comment by jean** [comment]
If @Tianchai doesn't grab it, I'll give it a go tonight.

**Comment by georgically** [comment]
Done
